version: 2

sources:
  - name: pacbook_raw
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('SNOWFLAKE_RAW_SCHEMA', 'RAW') }}"
    tables:
      - name: customer
      - name: address
      - name: address_status
      - name: country
      - name: customer_address
      - name: book
      - name: book_author
      - name: author
      - name: publisher
      - name: book_language
      - name: shipping_method
      - name: order_status
      - name: cust_order
      - name: order_line
      - name: order_history
